# Generated by Django 3.0.3 on 2021-03-23 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdfs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_publisher', models.CharField(max_length=255)),
                ('book_version', models.CharField(max_length=255)),
                ('book_subject', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Architechture', 'Architechture'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Javascript', 'Javascript')], default='C', max_length=50)),
                ('book_content', models.FileField(upload_to='books', validators=[pdfs.validators.validate_is_pdf])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
