# Generated by Django 3.0.3 on 2020-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_upload',
            name='book_subject',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('DBMS', 'DBMS')], default='C', max_length=50),
        ),
    ]
