# Generated by Django 3.0.3 on 2020-05-13 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfs', '0002_pdf_upload_book_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
