# Generated by Django 3.0.3 on 2021-03-03 12:04

from django.db import migrations, models
import pdfs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_auto_20200513_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='book_content',
            field=models.FileField(upload_to='books', validators=[pdfs.validators.validate_is_pdf]),
        ),
    ]
