# Generated by Django 3.0.3 on 2021-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0004_auto_20210303_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='book_subject',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Architechture', 'Architechture'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Javascript', 'Javascript')], default='C', max_length=50),
        ),
    ]
